cat /proc/uptime >> .uptime
xmodmap /home/master/.xmodmap &
tray &
wallpaper &
eval '$(gpg-agent --daemon)'
#(sleep 5 && parcellite) &
(sleep 5 && ~/.dropbox-dist/dropboxd ) &
(sleep 5 && mconky ) &
#(sleep 5 && firefox ) &
(sleep 5 && urxvt -T 'mutt') &
(sleep 5 && urxvt -T 'music') &
#urxvtd -q -o -f &
#(sleep 4 && wallpaper) &
#(sleep 2 && tint2) &
#exec openbox

urxvt &
export XDG_MENU_PREFIX=lxde- &
exec xmonad 
