syn on
"set relativenumber
set rnu
"set number 
set nocp
"
"set expandtab
"set shiftwidth=4
"set tabstop=4
"

"Linux Kernel
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab 
set diffopt+=iwhite
set smarttab                    "Indent instead of tab at start of line
set shiftround                  "Round spaces to nearest shiftwidth multiple
set nojoinspaces                "Don't convert spaces to tabs




vnoremap < <gv
vnoremap > >gv




"
set complete=.,w,b,u,t,i,d
"set foldmethod=syntax
"set foldlevel=1
"set foldnestmax=2

"set foldmethod=indent
set foldmethod=marker
set foldmarker={{{,}}}
set nowrap
set backspace=2
set showmatch
set ttyfast
set autowrite
set autoindent
set mouse=a
set mousehide
set encoding=utf8
set splitbelow


let mapleader=","
inoremap <leader>l <C-^>

noremap ; :
noremap : ;
noremap <space> za

noremap <F6> :cn<CR>
noremap <F7> :cp<CR>

noremap <F12> :NERDTreeToggle<CR>
let NERDTreeIgnore=['.*\.o$']
let NERDTreeIgnore+=['.*\.pyc$']
let NERDTreeIgnore+=['.*\.aux$']
let NERDTreeIgnore+=['.*\.pyg$']
let NERDTreeIgnore+=['.*\~$']
let NERDTreeIgnore+=['.*\.out$']
let NERDTreeIgnore+=['.*\.so$', '.*\.a$']


noremap <F11> :TlistToggle<CR>

noremap <F5> :make<CR>

nnoremap Y y$

nnoremap <buffer> <leader>e :call EvinceNearestLabel()<CR>
nnoremap <buffer> <LocalLeader>e :call EvinceNearestLabel()<CR>



" statusline -----------------------------------------------------------

set wildmenu
set incsearch
set hlsearch
set ignorecase
set smartcase
set scrolloff=5
set sidescrolloff=10
set shortmess=aOstT
set backup
set nohidden
set backupdir=~/.vim/backup
set directory=~/.vim/tmp
set cmdheight=1         " command line height
set laststatus=2        " condition to show status line, 2=always.
set ruler               " show cursor position in status line
set showmode            " show mode in status line
set showcmd             " show partial commands in status line
"set statusline=%r%h%w\ %([%{&ff}]%)%(:%y%)%(:[%{&fenc}]%)\ BUFF[%1.20n]%=%1.7l,%1.7c\ \ [%p%%]
" shows: filename, position, eof, syntax, encoding, format 
set statusline=%-3.3n\ %f\ %r%#Error#%m%#Statusline#\ (%l/%L,\ %c)\ %P%=%h%w\ %y\ [%1.20n]:[%{&encoding}:%{&fileformat}]\ 
set cursorline

set colorcolumn=80

set listchars=tab:,.,trail:.,extends:#,nbsp:. " Highlight problematic whitespace
set pastetoggle=<F12>


set tags=./tags;$HOME


let Tlist_Use_Right_Window=1





call pathogen#infect()

filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

   " let Vundle manage Vundle
   "  " required! 
Bundle 'gmarik/vundle'
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-markdown'
Bundle 'Lokaltog/vim-powerline'
Bundle 'AutoComplPop'
Bundle 'rosenfeld/conque-term'
Bundle 'scrooloose/nerdtree'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'jimenezrick/vimerl'
Bundle 'pyflakes.vim'
Bundle 'jonathanfilip/vim-lucius'

hi SignColumn ctermbg=none
hi SpellBad cterm=underline ctermbg=none ctermfg=10

filetype plugin indent on     " required!

let g:gitgutter_sign_column_always = 1

hi SignColumn  ctermfg=252     ctermbg=234     cterm=none      guifg=#e3e0d7   guibg=#242424   gui=none

if &term=~"linux"
    colo default
else
    set t_Co=256
    "colo wombat256mod
	"colo lucius
    "colo delek
    "colo slate
    "colo ir_black
    "colo vimbrant
    "colo hybrid
    "colo ir_black
    "colo molokai 
    "colo dante
    "colo zenburn 
    let g:lucius_style='dark'
    let g:lucius_contrast='low'
    colo lucius
endif

if has("gui_running")
    "colo zenburn 
    "colo candycode
    "colo ir_black
    "colo rdark
    "colo koehler
    "colo moria
    colo bclear
    "colo leo

    set guioptions-=T
    set guioptions-=L
    set guioptions-=m
    set guioptions-=r
    "set guifont=dejavu\ sans\ mono\ 10
    "set guifont=lucidaconsole\ 8
    set guifont=monospace\ 9
    "set guifont=monaco\ 8
    "set guifont=fixed\ 9
endif "has("gui_running")


if has("autocmd")

autocmd InsertLeave * set nopaste
autocmd BufWritePost .vimrc source %

"{{{"Templates for c and c++ files
autocmd BufNewFile *.c,*.cpp,*.h so /home/master/.vim/c_template
autocmd BufNewFile *.c,*.cpp,*.h exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.c,*.cpp,*.h exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.c,*.cpp,*.h execute "normal ma"
autocmd Bufwritepre,filewritepre *.c,*.cpp,*.h exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.c,*.cpp,*.h execute "normal `a"
autocmd BufNewFile,BufRead *.c,*.h setlocal foldmethod=syntax smartindent cinwords cinwords=if,else,for,do,while,switch
autocmd BufNewFile,BufRead *.cpp setlocal foldmethod=syntax smartindent cinwords cinwords=if,else,for,do,while,switch,class
"}}}

"{{{Templates and indentation for SML files
autocmd BufNewFile *.sml so /home/master/.vim/ml_template
autocmd BufNewFile *.sml exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.sml exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.sml execute "normal ma"
autocmd Bufwritepre,filewritepre *.sml exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost  *.sml execute "normal `a"
autocmd BufNewFile,BufRead *sml setlocal smartindent cinwords cinwords=fun,if,then,else,let,in,sig,struct,adstype,datatype,functor,structure,signature,case syntax=sml
"}}}

"{{{Templates and indentation for Erlang files
autocmd BufRead *.erl setlocal foldmethod=indent smartindent sw=4 ts=4 sts=4 expandtab
autocmd BufNewFile *.erl so /home/master/.vim/erlang_template
autocmd BufNewFile *.erl exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.erl exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.erl execute "normal ma"
autocmd Bufwritepre,filewritepre *.erl exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost  *.erl execute "normal `a"
"}}}
"
"{{{Templates and indentation for Haskell files
autocmd BufRead *.hs setlocal foldmethod=indent smartindent sw=2 ts=2 sts=2 expandtab
autocmd BufNewFile *.hs so /home/master/.vim/haskell_template
autocmd BufNewFile *.hs exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.hs exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.hs execute "normal ma"
autocmd Bufwritepre,filewritepre *.hs exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost  *.hs execute "normal `a"
autocmd BufNewFile,BufRead *.hs setlocal smartindent cinwords cinwords=fun,if,then,else,let,in,sig,struct,adstype,datatype,functor,structure,signature,case
"}}}

"{{{Templates indentation and syntax for prolog files
autocmd BufNewFile *.yap so /home/master/.vim/prolog_template
autocmd BufNewFile *.yap setlocal smartindent syntax=prolog
autocmd BufNewFile *.yap exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.yap exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.yap execute "normal ma"
autocmd Bufwritepre,filewritepre *.yap exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.yap execute "normal `a"
autocmd BufNewFile,BufRead *.yap setlocal smartindent syntax=prolog
"autocmd BufNewFile,BufRead *.yap colo slate
"}}}

"{{{Templates indentation and syntax for java
autocmd BufNewFile,BufRead *.java setlocal smartindent cinwords cinwords=if,else,for,do,while,switch,class,try,finally 
autocmd BufNewFile *.java so /home/master/.vim/java_template
autocmd BufNewFile *.java setlocal smartindent 
autocmd BufNewFile *.java exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.java exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.java execute "normal ma"
autocmd Bufwritepre,filewritepre *.java exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.java execute "normal `a"
"}}}

"{{{Templates indentation and syntax for cilk
autocmd BufNewFile *.cilk, so /home/master/.vim/c_template
autocmd BufRead,BufNewFile *.cilk setlocal syntax=cilk
autocmd BufNewFile *.cilk, exe "1," . 6 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.cilk, exe "1," . 6 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.cilk, execute "normal ma"
autocmd Bufwritepre,filewritepre *.cilk, exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.cilk, execute "normal `a"
autocmd BufNewFile,BufRead *.cilk setlocal foldmethod=syntax smartindent cinwords cinwords=if,else,for,do,while,switch
"}}}

"{{{Templates indentation and syntax for python
autocmd BufNewFile,BufRead *.py setlocal foldmethod=indent smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class sw=4 ts=4 expandtab
autocmd BufNewFile *.py so /home/master/.vim/python_template
autocmd BufNewFile *.py setlocal smartindent 
autocmd BufNewFile *.py exe "1," . 10 . "g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.py exe "1," . 10 . "g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd Bufwritepre,filewritepre *.py execute "normal ma"
autocmd Bufwritepre,filewritepre *.py exe "1," . 10 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.py execute "normal `a"
"}}}
"
"{{{Templates for pazcal
autocmd BufNewFile *.pzc,*pzh so /home/master/.vim/pazcal_template
autocmd BufNewFile *.pzc,*pzh  exe "1, 6  g/File Name :.*/s//File Name : " .expand("%")
autocmd BufNewFile *.pzc,*pzh  exe "1, 6  g/Creation Date :.*/s//Creation Date : " .strftime("%d-%m-%Y")
autocmd BufNewFile *.pzc,*pzh  exe "9, 11 g/pazcalprog/s/pazcalprog/" . expand("%:r") . "/"
autocmd BufNewFile *.pzc,*pzh  exe "9, 11 g/PROGRAM/s/PROGRAM [0-9-_]*/PROGRAM /"
autocmd Bufwritepre,filewritepre *.pzc,*pzh  execute "normal ma"
autocmd Bufwritepre,filewritepre *.pzc,*pzh  exe "1," . 6 . "g/Last Modified :.*/s/Last Modified :.*/Last Modified : " .strftime("%c")
autocmd bufwritepost,filewritepost *.pzc,*pzh  execute "normal `a"
"}}}

"{{{ Texing
"autocmd BufNewFile,BufRead *.tex setlocal keymap=greek
autocmd BufNewFile,BufRead *.tex setlocal smartindent tw=80
"autocmd BufNewFile,BufRead *.tex setlocal spell! spelllang=el,en<CR>
autocmd BufNewFile,BufRead *.tex setlocal spellsuggest=best,3
"}}}

"{{{ Blogging
autocmd BufNewFile *.markdown,*.md so /home/master/.vim/md_template
autocmd Bufwritepre,filewritepre *.markdown,*.md  execute "normal ma"
autocmd BufNewFile,Bufwritepre,filewritepre  *.markdown,*.md  exe "1, 3  g/Date:.*/s//Date: " .strftime("%Y-%m-%d %H:%M")
autocmd bufwritepost,filewritepost *.markdown,*.md  execute "normal `a"
autocmd BufNewFile,BufRead *.markdown,*.md setlocal smartindent tw=80
autocmd BufNewFile,BufRead *.markdown,*.md setlocal spell! spelllang=en_us
autocmd BufNewFile,BufRead *.markdown,*.md setlocal spellsuggest=best,3
"}}}
"
"{{{ Makefiles
autocmd BufNewFile Makefile,makefile so /home/master/.vim/makefile_template
autocmd BufNewFile,BufRead Makefile,makefile setlocal ts=8 sw=8 noet nosi noai
"}}}

"{{{ llama
autocmd BufRead *.lla setlocal syntax=llama
"}}}
"
"{{{ bob
autocmd BufRead *.bob setlocal syntax=c
"}}}
"
"{{{ mutt
"au BufRead /tmp/mutt-* setlocal tw=80
"au BufRead /tmp/mutt-* setlocal spell
"}}}

endif " has("autocmd")
